"""new fields in user model

Revision ID: 409df9a01a07
Revises: 9e0f23f35f29
Create Date: 2020-11-19 16:27:41.302355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409df9a01a07'
down_revision = '9e0f23f35f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
